# Generated by Django 5.0.6 on 2025-01-30 11:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Auth', '0003_rename_number_user_number_remove_company_opportunity'),
        ('post', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='opportunity',
            name='company',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='opportunty', to='Auth.company'),
        ),
    ]
