# Generated by Django 4.2.19 on 2025-03-03 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='opportunity',
            name='worktype',
            field=models.CharField(choices=[('Online', 'Online'), ('Onsite', 'Onsite'), ('Hybrid', 'Hybrid')], default='Onsite', max_length=20),
        ),
    ]
