# Generated by Django 5.0.6 on 2025-02-02 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='opportunity',
            name='category',
            field=models.CharField(choices=[('EC', 'Economics'), ('CS', 'Computer Science & IT'), ('EN', 'Engineering'), ('HL', 'Healthcare'), ('BM', 'Business & Management'), ('LW', 'Law'), ('ED', 'Education'), ('AH', 'Arts & Humanities')], max_length=30),
        ),
    ]
