# Generated by Django 5.0.6 on 2025-01-30 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Auth', '0003_rename_number_user_number_remove_company_opportunity'),
        ('post', '0003_alter_opportunity_company'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='students',
            field=models.ManyToManyField(null=True, related_name='teams', to='Auth.student'),
        ),
    ]
