# Generated by Django 5.0.6 on 2025-02-02 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0003_alter_application_student_alter_application_team'),
    ]

    operations = [
        migrations.AddField(
            model_name='opportunity',
            name='daysleft',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='application',
            name='status',
            field=models.CharField(choices=[('submitted', 'Submitted'), ('under_review', 'Under Review'), ('accepted', 'Accepted'), ('rejected', 'Rejected')], default='submitted', max_length=20),
        ),
    ]
