# Generated by Django 5.0.6 on 2025-02-16 07:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('application', '0001_initial'),
        ('post', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='team',
            field=models.ForeignKey(null=1, on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='post.team'),
        ),
    ]
