# Generated by Django 4.2.19 on 2025-02-19 11:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('application', '0001_initial'),
        ('post', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='team',
            field=models.ForeignKey(null=1, on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='post.team'),
        ),
    ]
