# Generated by Django 4.2.19 on 2025-02-25 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='atachedfile',
            field=models.URLField(blank=True, null=True),
        ),
    ]
