# Generated by Django 5.0.6 on 2025-02-16 10:10

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='acceptedby',
            field=models.ManyToManyField(null=True, to=settings.AUTH_USER_MODEL, verbose_name='accepteduser'),
        ),
    ]
