# Generated by Django 5.0.6 on 2025-01-31 20:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('EC', 'Economics'), ('CS', 'Computer Science & IT'), ('EN', 'Engineering'), ('HL', 'Healthcare'), ('BM', 'Business & Management'), ('LW', 'Law'), ('ED', 'Education'), ('AH', 'Arts & Humanities')], max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Skills',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(unique=1)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('education', models.CharField(max_length=50)),
                ('gendre', models.CharField(choices=[('M', 'Men'), ('F', 'Female'), ('P', 'Prefer not to say')], default='P', max_length=50)),
                ('category', models.CharField(choices=[('EC', 'Economics'), ('CS', 'Computer Science & IT'), ('EN', 'Engineering'), ('HL', 'Healthcare'), ('BM', 'Business & Management'), ('LW', 'Law'), ('ED', 'Education'), ('AH', 'Arts & Humanities')], max_length=50)),
                ('rating', models.IntegerField(default=5)),
                ('skills', models.ManyToManyField(to='Auth.skills', verbose_name='Skills')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('place', models.CharField(max_length=50, null=True)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('email', models.EmailField(max_length=100, unique=True)),
                ('password', models.CharField(max_length=100)),
                ('number', models.IntegerField(null=True)),
                ('profilepic', models.ImageField(null=True, upload_to='images')),
                ('type', models.CharField(choices=[('Student', 'Student'), ('Company', 'Company'), ('Admin', 'Admin')], max_length=50)),
                ('date_joined', models.DateField(auto_now_add=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('is_superuser', models.BooleanField(default=False)),
                ('company', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user', to='Auth.company', verbose_name='company')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('student', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user', to='Auth.student', verbose_name='Students')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
