# Generated by Django 5.0.6 on 2025-01-29 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('EC', 'Economics'), ('CS', 'Computer Science & IT'), ('EN', 'Engineering'), ('HL', 'Healthcare'), ('BM', 'Business & Management'), ('LW', 'Law'), ('ED', 'Education'), ('AH', 'Arts & Humanities')], max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Skills',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('education', models.CharField(max_length=50, null=True)),
                ('gendre', models.CharField(choices=[('M', 'Men'), ('F', 'Female'), ('P', 'Prefer not to say')], default='P', max_length=50)),
                ('category', models.CharField(choices=[('EC', 'Economics'), ('CS', 'Computer Science & IT'), ('EN', 'Engineering'), ('HL', 'Healthcare'), ('BM', 'Business & Management'), ('LW', 'Law'), ('ED', 'Education'), ('AH', 'Arts & Humanities')], max_length=50)),
                ('rating', models.IntegerField(default=5)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('email', models.EmailField(max_length=100, unique=True)),
                ('password', models.CharField(max_length=100)),
                ('Number', models.IntegerField(null=True)),
                ('profilepic', models.ImageField(upload_to='images')),
                ('type', models.CharField(choices=[('Student', 'Student'), ('Company', 'Company')], max_length=50)),
                ('date_joined', models.DateTimeField(auto_now_add=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('is_superuser', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
