# Generated by Django 5.0.6 on 2025-01-28 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Auth', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='education',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='Skills',
            field=models.ManyToManyField(null=True, to='Auth.skills', verbose_name='Skills'),
        ),
        migrations.AlterField(
            model_name='student',
            name='rating',
            field=models.IntegerField(default=5),
        ),
    ]
