# Generated by Django 5.0.6 on 2025-01-29 09:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Auth', '0001_initial'),
        ('auth', '0012_alter_user_first_name_max_length'),
        ('post', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='opportunity',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='post.opportunity', verbose_name='oppertune'),
        ),
        migrations.AddField(
            model_name='student',
            name='Skills',
            field=models.ManyToManyField(null=True, to='Auth.skills', verbose_name='Skills'),
        ),
        migrations.AddField(
            model_name='user',
            name='Student',
            field=models.OneToOneField(null=1, on_delete=django.db.models.deletion.CASCADE, to='Auth.student', verbose_name='Students'),
        ),
        migrations.AddField(
            model_name='user',
            name='company',
            field=models.OneToOneField(null=1, on_delete=django.db.models.deletion.CASCADE, to='Auth.company', verbose_name='company'),
        ),
        migrations.AddField(
            model_name='user',
            name='groups',
            field=models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups'),
        ),
        migrations.AddField(
            model_name='user',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions'),
        ),
    ]
