# Generated by Django 5.0.6 on 2025-01-30 11:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Auth', '0002_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='Number',
            new_name='number',
        ),
        migrations.RemoveField(
            model_name='company',
            name='opportunity',
        ),
    ]
