# Generated by Django 4.2.19 on 2025-02-25 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Auth', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='cv',
            field=models.URLField(null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='profilepic',
            field=models.URLField(max_length=1000, null=True),
        ),
    ]
