# Generated by Django 4.2.19 on 2025-02-24 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Auth', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='notfications',
            name='isseen',
            field=models.BooleanField(default=False),
        ),
    ]
