# Generated by Django 5.0.6 on 2025-01-30 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Auth', '0002_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='Number',
            new_name='number',
        ),
        migrations.AlterField(
            model_name='skills',
            name='name',
            field=models.TextField(unique=1),
        ),
    ]
