# Generated by Django 5.0.6 on 2025-01-29 10:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Auth', '0002_initial'),
        ('post', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='opportunity',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='post.opportunity', verbose_name='oppertune'),
        ),
        migrations.AlterField(
            model_name='student',
            name='Skills',
            field=models.ManyToManyField(to='Auth.skills', verbose_name='Skills'),
        ),
    ]
