# Generated by Django 5.0.6 on 2025-02-01 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Auth', '0002_user_savedposts_notfications'),
        ('post', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='savedposts',
            field=models.ManyToManyField(to='post.opportunity', verbose_name='opportunity'),
        ),
    ]
