# Generated by Django 5.0.6 on 2025-02-01 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Auth', '0003_alter_user_savedposts'),
        ('post', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='savedposts',
        ),
        migrations.AddField(
            model_name='student',
            name='savedposts',
            field=models.ManyToManyField(to='post.opportunity', verbose_name='opportunity'),
        ),
    ]
