# Generated by Django 5.0.6 on 2025-01-30 12:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Auth', '0003_rename_number_user_number_remove_company_opportunity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='company',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user', to='Auth.company', verbose_name='company'),
        ),
        migrations.AlterField(
            model_name='user',
            name='student',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user', to='Auth.student', verbose_name='Students'),
        ),
    ]
