# Generated by Django 4.2.19 on 2025-02-25 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Auth', '0003_alter_student_cv_alter_user_profilepic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='cv',
            field=models.URLField(max_length=1000, null=True),
        ),
    ]
