# Generated by Django 5.0.6 on 2025-02-02 21:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Auth', '0006_alter_mcf_token_alter_mcf_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mcf',
            name='token',
            field=models.CharField(max_length=500, unique=True),
        ),
        migrations.AlterField(
            model_name='mcf',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name=''),
        ),
    ]
