# Generated by Django 5.0.6 on 2025-02-02 22:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Auth', '0007_alter_mcf_token_alter_mcf_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mcf',
            name='user',
            field=models.ForeignKey(null=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name=''),
        ),
    ]
